trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
printWidth: 200
useTabs: false
bracketSpacing: true
arrowParens: 'avoid'
htmlWhitespaceSensitivity: 'ignore'

overrides:
    - files:
          - '*.yml'
          - '*.yaml'
      options:
          tabWidth: 4
